<template>
  <el-dialog
    title="Service Agreement"
    :visible="visible"
    width="70%"
    :before-close="handleClose"
    fullscreen
  >
    <p>Welcome to rongbaoge platform！</p>
    <h2>【Careful reading】</h2>
    <p>Please carefully read and fully understand the terms and conditions of this agreement, including:</p>
    <p>1. Agree with you to exempt or limit liability;</p>
    <p>2. Agree with you on the terms of law application and jurisdiction;</p>
    <p>3. Other important terms marked with bold underline.</p>
    <p>If you have any questions about the agreement, please contact the customer service of the Platform.</p>
    <h2>【special suggestion】</h2>
    <p>When you fill in the information, read and agree to the Agreement as prompted on the registration page, and complete all registration procedures, it means that you have fully read, understand and accept all contents of the Agreement.If you use rongbaoge platform services,Should follow the law of the People's Republic of China on the network safety ", "copyright law of the People's Republic of China" and "information network transmission right protection ordinance (2006)," copyright collective management regulations (2004) ", "implementing regulations of the People's Republic of China copyright law", "the implementation of the provisions of the international copyright treaty (1992), the world intellectual property organization copyrightTreaty (1996), Regulations on the Management of Blockchain Information Services, User Registration Agreement of Rongbaoge Platform and other relevant agreements of Rongbaoge Platform.Any dispute between you and other users or any third party during the use of rongbaoge platform services will be handled in accordance with the agreement reached between you and other users or any third party.</p>
    <p>During reading this Agreement, if you do not agree with the agreement or any of its provisions, you should immediately stop the registration process.</p>
    <h3>Article 1 General Provisions </h3 >
    <p>1. Rongbaoge Platform is operated by Nantong Honglian Information Technology Co., LTD. (hereinafter referred to as "Honglian Technology"), specializing in providing services including but not limited to block chain value-added, digital works collection and other services. The specific service content is provided by Rongbaoge platform according to the actual situation.</p>
    <p>2. Rongbaoge Platform User Registration Agreement (hereinafter referred to as the "Agreement") is an online agreement entered into between you and Honglink Technology regarding the registration and use of Rongbaoge Platform.</p>
    <p>3. Users of Rongbaoge Platform refer to natural persons, legal persons or other organizations who are voluntarily bound by this Agreement and all rules of Rongbaoge and registered as users of the Platform in accordance with relevant procedures of the Platform, so as to be qualified to enjoy relevant services provided by the Platform.</p>
    <p>4. This Agreement can be updated by Rongbaoge platform as required, and you should pay attention to it and agree to it in time.Notices, announcements, statements, rules, management measures or other rules of Rongbaoge Platform shall be an integral part of this Agreement and shall be deemed to have been read and accepted by you upon publication by rongbaoge Platform and shall have legal effect on you.If you do not accept the modification of this Agreement, please immediately cancel the registered information, rongbaoge platform will immediately stop serving you.</p>
     <h3> Second definition </h3>
    <p>1. The term "work" in this Agreement refers to the work as defined in the Copyright Law and relevant Chinese laws and regulations.</p>
    <p>2. The term "copyright" as used in this Agreement means the legal rights of author or other persons (including legal persons) to a work under the Copyright Act.</p>
    <p>3. NFT (Non-fungible Token) referred to in this Agreement refers to the unique digital asset corresponding to the copyright of the works of the copyright owner formed after the digitalization of the works through technology.</p>
    <p>4. The copyright registration service mentioned in this Agreement means that the copyright registration certificate issued by the Copyright Bureau is obtained by the application of the right holder through rongbaoge platform and after examination by the Copyright Bureau.</p>
    <p>5. The term "copyright depositing service" in this Agreement refers to the service of recording and depositing the work information provided by the right holder through rongbaoge platform, which is applied for by the right holder, by Honglian Technology through the timing server.</p>
    <p>6. The copyright trading service referred to in this Agreement refers to the intermediary and platform service provided by Rongbaoge platform for users to purchase copyright of the works of the right owner, including the matching of copyright authorization and transfer, payment collection and payment, transaction witness and storage, etc.</p>
    <p>7. The NFT Transaction Service mentioned in this Agreement refers to the transaction matching service provided by Rongbaoge platform for users to purchase copyright NFT of works of owners.</p>
    <p>8. The copyright monitoring service referred to in this Agreement refers to the information collection and statistical analysis service provided by Rongbaoge Platform on the release, reading, broadcasting, reprinting, use of materials and other situations of designated works or works set on the Internet.</p>
    <p>9. The copyright protection service mentioned in this Agreement refers to the cooperation or entrustment between Rongbaoge Platform and third-party law firm, notary office, arbitration bureau, anti-infringement alliance, content platform, etc., to provide the right holder with the services of cracking down on and stopping copyright infringement, claiming loss, legal litigation, etc.</p>
    <p>10. The term "Copyright valuation Service" in this Agreement refers to the service provided by Rongbaoge Platform to assess the copyright value of the works.</p>
    <p>11. The international copyright services referred to in this Agreement shall guide the entry of foreign works copyright, domestic works copyright to go abroad, foreign works domestic rights protection, domestic works overseas rights protection and other services.</p>
    <h3> Article 3 Account Registration and Management</h3>
    <p>1, user qualification </p>
    <p> When you register your Rongbaoge platform account, you shall have the capacity for civil conduct in accordance with the laws of the People's Republic of China.If you do not have the capacity for civil conduct as aforesaid, you or your guardian shall bear all legal consequences arising therefrom in accordance with the provisions of the law.</p>
    <p>2, account get </p>
    <p> When you fill in the correct and complete information, read and agree to this Agreement as prompted on the registration page, and complete all registration procedures, this Agreement will come into force, and you can obtain an account of Rongbaoge Platform and become a rongbaoge platform user.After you become a rongbaoge platform user, you are bound by this agreement. When you use the special services and products of Rongbaoge platform, you should agree and accept the relevant service agreement before you can use them.</p>
    <p>3. Account transfer </p>
    <p> As the user account is associated with the credit information of the user, you can transfer your account only when it is expressly stipulated by law, adjudicated by the judiciary or agreed in writing by Rongbaoge Platform, and in accordance with the account transfer process stipulated by rongbaoge Platform rules.Otherwise, your account shall not be transferred in any way, and any behavior under your account name shall be regarded as a transaction conducted by you, and all liabilities arising therefrom shall be borne by you.</p>
    <p>4. Real-name authentication </p>
    <p> The law does not grant Rongbaoge platform the right to require users to perform real-name authentication, but in order to enable you to better experience the services of Rongbaoge Platform, Rongbaoge platform suggests that you complete real-name authentication in accordance with the requirements of Rongbaoge platform and the provisions of Chinese laws.All legal liabilities and consequences caused by your failure to conduct real name authentication shall be borne by you and have nothing to do with Rongbaoge Platform.</p>
    <p>5. Account management </p >
  <p> The user name you set shall not violate the user management provisions of national laws and regulations, otherwise Rongbaoge Platform has the right to withdraw or disable your account.If your account is disabled by Rongbaoge platform due to violation of relevant regulations, you can apply to change the user name, rongbaoge platform after review to resume use.</p>
    <p> 6. Account information </p>
    <p> you should fill out the registration information according to the requirement of the RongBaoGe platform, to disclose the information or any other identity information (including but not limited to your name/company name, id card/business license and contact phone number, address and email, etc.), and shall ensure that the information provided by or true, complete, accurate and effective information, such as have change, should be timely update related information or data.If the information provided by you is inaccurate, untrue or fails to timely change the relevant information or information, the legal consequences and losses, including the relevant legal liabilities to Rongbaoge or any third party, will be borne by you.</p>
    <p>7, account security </p>
    <p>Your account is set up and properly kept by you, and you shall be liable for any loss and consequences caused by illegal use of your account and password by others due to hacking or your negligence in keeping, or disclosure of your account by yourself, attack or fraud by others, etc.If you find that your account is illegally used by others, you should immediately notify Rongbaoge platform.If you fail to timely inform Rongbaoge Platform, you shall be responsible for all the results of your actions under your account (including but not limited to signing various agreements online, releasing information, authorizing copyright, purchasing copyright, etc.), and you shall be liable for any loss caused to you or a third party in the later period.</p>
 <h3> Article 4 User's Commitment and Warranty </h3>
    <p>1. You voluntarily apply to become a rongbaoge platform user and abide by the rules and mechanisms of Rongbaoge Platform.</p>
    <p>2. When you use the services of Rongbaoge Platform, you shall abide by the service specifications of Rongbaoge Platform, including but not limited to Rongbaoge User Registration Agreement.</p>
    <p>3. You confirm that you have read and voluntarily abide by Chinese laws and regulations, departmental rules and regulations and rules related to Rongboge Platform, and accept the revision of business rules related to Rongboge Platform by Honglink Technology and notify you of the revised content in the form of announcement or other forms on the official website of Rongboge Platform.</p>
    <p>4. You guarantee that you are fully responsible for the content provided and shall not upload or trade any works containing any of the following contents on Rongbaoge Platform. Otherwise, Rongbaoge Platform has the right to handle the works without notice:</p>
    <ul>
      <li>(1) violating the basic principles established by the Constitution;</li>
      <li>(2) endangering national security, leaking state secrets, subverting state power, or undermining national unity;</li>
      <li>(3) damages the honor and interests of the State;</li>
      <li>(4) inciting ethnic hatred or discrimination or undermining ethnic unity;</li>
      <li>(5) sabotaging the state's religious policies and propagating heresies and feudal superstitions;</li>
      <li>(6) those who spread rumors, disturb social order and undermine social stability;</li>
      <li>(7) spreading obscenity, pornography, gambling, violence, terrorism or abetting a crime;</li>
      <li>(8) insulting or slandering others or infringing upon the lawful rights and interests of others;</li>
      <li>(9) inciting illegal assembly, association, procession, demonstration or gathering of people to disturb public order;</li>
      <li>(10) activities in the name of illegal non-governmental organizations;</li>
      <li>(11) contains other contents prohibited by laws and administrative regulations.</li>
    </ul>
    <p> 5, you should guarantee the copyright authorization, license by RongBaoGe platform of all the works enjoy complete intellectual property rights, or has already been authorized holder of the relevant works (including but not limited to position, commissioned works or cooperative work), is toward treasure cabinet platform provides real legal and valid license text, certificate, etc.Any third party dispute, claim, compensation or lawsuit caused by violation of this article shall be borne by you, and rongbaoge platform is not involved.If a third party claims against the Trading Platform due to its violation of this Provision, you shall indemnify Rongbaoge Platform for all losses (including but not limited to damages, legal costs, attorney's fees and other relevant reasonable expenses).</p>
    <p> 6. Users have the right to apply to Rongbaoge Platform for deleting uploaded works at any time, and Rongbaoge Platform may, at its own discretion, delete any works that violate laws, regulations, provisions of this Agreement and relevant rules of Rongbaoge Platform.When a third party believes that your copyright authorization or licensing works may constitute infringement and sends a notice of rights to this Site in accordance with the Regulations on the Protection of The Right of Communication through Information Network or relevant laws, you agree and authorize Rongbaoge Platform to make its own judgment and decide to delete the suspected infringing works.Rongbaoge platform has no obligation to restore the deleted content unless you submit written evidence with sufficient validity to exclude the possibility of infringement.</p>
    <p> 7, you ensure that when RongBaoGe platform using the web service may not be in violation of the provisions of the following, otherwise RongBaoGe platform has the right to require you to correct or directly to take all necessary measures (including but not limited to delete uploaded authorized work, information, and provide the right to suspend or terminate the use of a web service) in order to reduce the impact of your wrongdoing: </p>
    <ul>
      <li>(1) Comply with relevant laws and regulations currently in force in China;</li>
      <li> (2) Comply with all network protocols, regulations and procedures relating to network services;</li>
      <li> (3) Shall not provide false information or materials;</li>
      <li>(4) Do not use the network service system of Rongbaoge Platform for any illegal purpose;</li>
      <li>(5) Do not use Rongbaoge platform to conduct any behavior that may adversely affect the normal operation of the Internet;</li>
      <li>(6) Do not use Rongbaoge platform to conduct any behavior that is not conducive to the trading platform;</li>
      <li>(7) Shall not use Rongbaoge Platform to conduct any behavior that seriously damages the normal operation order of Rongbaoge Platform and China Copyright Blockchain Alliance, or affects the normal trading order of the market;</li>
    </ul>
    <p>8. You guarantee that you will exercise all rights obtained through Rongbaoge Platform in accordance with Chinese laws and regulations and rules of Rongbaoge Platform, and you shall bear all consequences caused by your improper use.</p>
    <p>9. You guarantee that the source of funds involved in copyright trading and other paid services on Rongbaoge platform is legitimate, otherwise you shall be solely responsible for all legal consequences and liabilities arising therefrom.</p>
    <p>10. You shall ensure the safety and reliability of the equipment used for payment.All legal consequences and economic losses caused by your equipment failure, communication failure and other reasons shall be borne by you.</p>
    <p>11. You agree and authorize Rongbaoge Platform to transfer the transaction price between your trading account and other trading accounts according to the transaction information, handle tax-related matters, etc., and agree to pay transaction service fee, storage fee, and other service fees in accordance with the relevant provisions of Rongbaoge Platform.</p>
    <p>12. You agree and authorize Rongbaoge Platform and its associated service providers or any third party entrusted by either party to understand, consult and examine the true situation of transaction risks of users in the individual market through legal channels (including but not limited to credit investigation agencies), and judge the risk status of users accordingly.</p>
    <p>13. You promise to properly keep your trading account number, trading password and relevant confidential documents, and you will be liable for any loss caused by disclosure.</p>
    <h3>Article 5 Rongbaoge Platform commitment and guarantee</h3>
    <p>1. Rongbaoge Platform undertakes that it shall strictly abide by the provisions of national laws and regulations and various departmental rules and regulations, and is willing to be bound by all terms of this Agreement.</p>
    <p>2. Rongbaoge Platform ensures that it has taken reasonable and effective technical measures to protect the security of your account information, data and trading activities.Nevertheless, in line with the attitude of being responsible for you, Rongbaoge platform solemnly reminds you that unpredictable risks objectively still exist.</p>
    <p>3. Rongbaoge Platform undertakes to keep your account information, data and transaction activities confidential, except for the following circumstances:</p>
    <ul>
      <li> (1) Obtain your express prior authorization;</li>
      <li> (2) as required by the laws or administrative regulations and rules of the People's Republic of China;</li>
      <li> (3) at the request of the State security organs, public security departments or other authorities of the People's Republic of China, or in accordance with the corresponding legal procedures;</li>
      <li> (4) In case of emergency, in order to maintain the safety and order of users, other social individuals or the public, for the purpose of maintaining the public interest;</li>
      <li> (5) To safeguard the legitimate rights and interests of Rongbaoge Platform.</li>
    </ul>
    <p>4, in order to promote the service quality of RongBaoGe platform, RongBaoGe may cooperate with a third party to provide relevant services for you, may need to include, but are not limited to such cooperation RongBaoGe platform user data traffic with third-party user data, in this case, you know and agree that if the third party agreed to take responsibility for and RongBaoGe equal responsibility to protect the privacy of your information,Rongbaoge has the right to provide your account information, data and Rongbaoge activities to such third party, and agree with such third party that the data will only be used for the purpose of the Rongbaoge platform services between the parties;Furthermore, Rongbaoge will monitor and manage the use of data by such third parties and make every reasonable effort to protect the security of your information.Although great efforts have been made to protect your account and other information, there is still no guarantee that the existing security measures can protect your technical information from any form of loss.</p>
    <h3> Article 6 Service Contents </h3>
  <p>1. Rongbaoge platform provides you with the following services, including but not limited to: uploading copyright of works to blockchain depository service (hereinafter referred to as "Copyright Depository Service");Copyright registration services (" Copyright Registration Services ");Trading services for copyright works (hereinafter referred to as "Copyright Trading Services");Whole-network monitoring service for copyright works (hereinafter referred to as "Copyright Monitoring Service");Evidence collection service for copyright infringement (hereinafter referred to as "Evidence collection Service for Infringement");Judicial certification service of tort evidence (hereinafter referred to as "judicial certification service");Legal rights protection services for copyright works (hereinafter referred to as "legal Rights protection Services");Copyright NFT Transaction Matching Service (" NFT Transaction Matching Service ");Other technologies and/or services provided by our Platform (" Other Technologies and Services ").The specific charging standard of copyright depositing service, copyright registration service, copyright trading service, copyright monitoring service, infringement evidence collection service, judicial certificate issuing service, legal rights protection service and other services shall be subject to the price published on the official website. Our platform has the right to adjust the charging standard independently according to the market situation.</p>
  <p>2. The services of Rongbaoge Platform are limited to your use on Rongbaoge Platform. Any act of separating our services from Rongbaoge Platform by malicious cracking or other illegal means does not belong to our services as agreed herein.All the legal consequences arising therefrom shall be held responsible by the actor, and we will investigate the actor's legal liability according to law.</p>
  <p> 3, our platform website official way for registered and logged in to use our service the only legal way, your way through any other channel, any way, any access to our services (including but not limited to, account, integral, experience value, integral goods, exchange goods, gifts, downloads, etc.) are illegally obtained, we will not acknowledge its validity,And once found, we have the right to immediately delete, cancel, clear, seal the number, etc., and you shall be liable for all adverse consequences caused thereby.We reserve the right to pursue legal liability to relevant responsible subjects.</p>
  <p>4. We have the right to make announcements to users (including but not limited to pop-up pages, website announcements, website messages, etc.) to modify, replace or upgrade any software related to rongbaoge platform services.If you do not agree or accept the modification, replacement or upgrade of the software related to the services of Rongbaoge Platform, please directly reject, stop or cancel, otherwise you will be deemed to have agreed and accepted the modification, replacement or upgrade of the software related to Rongbaoge platform, and the actions agreed and accepted will still be bound by this Agreement.</p>
  <p>5, you understand and recognition, and you to use our platform obtained the use of web site or platform for our account records, subscriptions, the collection, integration, experience value, growth, value, rank, identity, coupons, and virtual integration, virtual exchange goods goods, virtual gifts, download, such as derivatives, you confirm it doesn't, enjoy the ownership (unless otherwise notice that our platform),We permit you to use according to the rules of Rongbaoge platform.Rongbaoge platform shall assume corresponding responsibilities in case of specific provisions of laws.</p>
  <p>6. You agree and warrant that you shall not use the services of our platform or its derivatives (including but not limited to account, points, grades, points products, event gifts, downloads and other services) to resold, resold, replace, or mortgage for any illegal profit.You will not use the services of our platform or its derivatives to infringe the legitimate rights and interests of others, and it is forbidden to steal or embezzle others' accounts, points and points products through network vulnerabilities, malicious software or other illegal means.</p>
  <p> 7, you understand and approved, if the user through the third-party payment tools in our platform account after payment or prepaid phone may produce any commercial risks (including but not limited to the use of your account or bank card and other negotiable card for illegal activities, such as the third party on behalf of prepaid phone again after a refund to your member rights cannot be realized;Using third-party black channels to prepaid phone, or through a third party informal channels to purchase is far lower than the market value of RongBaoGe platform members rights, etc.), such as the risk could cause you corresponding economic losses, we fully perform its obligations under this agreement and in accordance with the law under the premise of the law has clear provisions and within the scope of the condition of the bear corresponding responsibility.</p><h3>Article 7 Service Agreement </h3>
  <p>1. Uploading and storing of user works </p>
  <p> You can upload your works on our platform for copyright storage, including but not limited to text, graphics, pictures, video, audio and other copyright works in accordance with the provisions of the copyright law, but you need to bear relevant legal liabilities for these works.We shall bear the corresponding responsibilities if the law clearly stipulates.</p>
    <p>2. Authorized use of copyright of user's works</p>
    <ul>
      <li>2.1 Unless otherwise demonstrated, copyright or other forms of copyright-based NFT digital assets purchased on our platform automatically become the copyright owner of the corresponding WORKS of the NFT.Unless otherwise agreed by both parties, if you check the service Agreement when registering rongbaoge platform, it means that you have the right and agree to grant the copyright free of charge throughout the world during the copyright validity period (unless you take the initiative to delete or require our platform to remove related works).We have the right to store, use, publish, copy, modify, adapt, publish, translate, create derivative works based on the content, disseminate, perform and display the content;The right to incorporate all or part of the content into any other form of work, media or technology;The right to commercial development of your uploaded and published content;And the right to sublicense the uploaded content to other third parties for use in the above manner, with prior notice and with your express consent.</li>
      <li>2.2 As the copyright owner, you, as the platform owner, shall be entitled to enjoy the profits from the secondary licensed development or operation of the platform based on your copyright. The specific proportion of such profits shall be subject to the actual situation.</li>
      <li>2.3 You must guarantee that the works deposited with us do not infringe the right of portrait, copyright, copyright or other rights of any third party.You must guarantee that there will be no disputes over copyright, portrait right or property right with any third party when we use the work authorized.If any third party claims for rights, you should eliminate them in time according to law, otherwise you shall bear all legal liabilities and all losses caused to us.</li>
      <li>2.4 If there is an authorized agency, you authorize us to represent the works, you have the right of publication in the industry you belong to, and we have no right to interfere.</li>
      <li> 2.5 in expressly inform and ask for your permission, we have the right to review, screening, editing of product, promotion, has the right to refuse the promotion or distribution does not conform to our technical requirements, we think that is outdated or wrong, obscene, libel or slander, indecent, or intellectual property problems of works;Modify, edit and classify products according to the requirements and specifications of our company or cooperative channels.</li>
    </ul>
    <p>3. User information association </p>
    <p> in order to facilitate your use of other related services, we and our affiliates you authorization we will you register account and use our platform service providing, in the process of formation of the information to our affiliates and other related services provider, or from our affiliates and other related services provider for you provide during registration, using the related service, the formation of the information,We obtain such information so that you can enjoy consistent experience and services on the websites or service platforms of us and our affiliated companies.</p>
    <p>4, users upload content disclaimer </p>
    <p> You understand and acknowledge that you have access to content and information from a wide range of sources when using our platform services, and we are not responsible for the accuracy, authenticity, availability, security, integrity or legitimacy of such content and information.You understand and acknowledge that you may be exposed to incorrect, offensive, inappropriate or offensive content and information, and you will not hold us liable accordingly.We do not endorse, recommend or express opinions on any content and information uploaded, published or transmitted by you on our Platform, nor do we assume any responsibility for errors, flaws, loss or damage caused by any content and information. Any use of the Content and information shall be at your own risk.Our platform shall assume corresponding responsibilities in case of specific provisions of laws.</p>
    <p>5. Advertising and promotional information </p>
    <p> You agree that in the course of providing the Services, we may place commercial advertisements or any other type of commercial information in any manner (including but not limited to placing advertisements on any location on our platform and placing advertisements in the content uploaded or disseminated by users),You agree to accept promotional or other relevant commercial information sent to you by us via email, site SMS, mobile phone SMS, website announcement or other means.If you no longer agree to the above SMS, email or message sent to you by our platform, please notify our platform clearly by unsubscribing SMS or email or in writing.</p>
    <p>6. Abide by laws and regulations
    <p> You agree to abide by the following laws and regulations when using our platform services:"Network security law of the People's Republic of China, the law of the People's Republic of China law on guarding state secrets, the law of the People's Republic of China copyright law, the law of the People's Republic of China computer information system safety protection regulations", the computer software protection ordinance, "Internet electronic bulletin service management regulations", the information network transmission right protection ordinance and other related to computers and the InternetPrescribed laws and regulations.In any case, if we have evidence that your behavior may violate the above laws and regulations, we shall have the right to determine your behavior and the applicable rules and deal with you accordingly, and terminate the services to you without prior notice.</p>
    <h3> Article 8 Disclaimer </h3 >
    <p>contents of this Agreement, and that Rongbaoge platform will not be liable for any losses caused by risks that do not belong to Rongbaoge platform.</p>
    <p>2. Whereas Rongbaoge platform only provides users with Internet copyright services and an open platform for publicity, and does not participate in actual transactions between users, documents, pictures, videos, audio and other content files accumulated or traded on the platform are all from users.Rongbaoge platform does not edit or modify uploaded documents, pictures, videos, audio and other content files.In case of any dispute between you and one or more other users or any dispute with any other right holder arising from any authorization transaction or copyright announcement, you shall fully compensate and bear relevant legal liabilities for any claim, demand or damage arising or possible arising from such dispute. Rongbaoge platform shall not bear any liability for such dispute.</p>
    <p>3. All linked websites of Rongbaoge platform are independently operated websites. Rongbaoge cannot guarantee that the linked websites you browse are safe, legal and effective.Rongbaoge platform has nothing to do with the interaction and transaction between you and each user, and Rongbaoge platform will be exempt from all consequences arising therefrom.</p>
    <p> 4. Rongbaoge Service may change the Service or delete some of its functions at any time for any reason.Rongbaoge service may cancel or terminate the service for the user at any time.No reason or notice is required to cancel or terminate the Rongbo Pavilion service.Once the service is cancelled, the user's right to use the Service terminates immediately.In the event of cancellation or termination of the Service, any information stored by the user in the Service may not be restored.</p>
    <p>5. In view of the special nature of Internet services, you acknowledge and agree that Rongbaoge has the right to change, interrupt or terminate part or all of the Internet services at any time without notice or liability according to the business development situation.</p>
    <p>6. Rongbao Pavilion needs to overhaul or maintain the provided Rongbao Pavilion platform or related equipment periodically or irregularly. If the service is interrupted within a reasonable time due to such circumstances, Rongbao Pavilion shall not be liable for any such interruption, but Rongbao Pavilion will notify as far as possible in advance.</p>
    <p>7. Rongbaoge does not assume any responsibility for service interruption or other defects of Rongbaoge platform caused by force majeure or reasons beyond rongbaoge's control, but rongbaoge will try its best to reduce the loss and influence caused to you.</p>
    <p>8. Rongbaoge Service may change the Service or delete some of its functions at any time for any reason.Prosperity Pavilion service may cancel or terminate your service at any time.You do not need a reason or notice to cancel or terminate your service.Once the service is cancelled, your right to use the Service terminates immediately.Any information you have stored in the Service may not be restored once the Service is cancelled or terminated.</p>
    <p>9. Exemptions referred to in other provisions of this Agreement.</p>
    <h3>Article 9 Entrustment and authorization of safeguarding rights</h3>
    <p> 1. Copyright protection services are a series of legal services provided by Rongbaoge Platform for registered users to protect their legitimate rights and interests of copyright.</p>
    <p> 2. When Rongbaoge detects any infringement of your work through the existing technical means of the Platform, Rongbaoge will take the lead in informing you of the detected infringement.You have the right to choose whether to entrust the platform to start online rights protection service after knowing the infringement event.If you choose not to start the online rights protection service provided by Rongbaoge Platform, the copyright certificate provided by Rongbaoge platform for your work and can be used as evidence to prove the ownership of your own rights protection;If you choose to authorize RongBaoGe platform to infringe on copyright and the rights of copyright and related rights behavior, is seen as agreed RongBaoGe platform entrusted rights related rules, and accept RongBaoGe platform on the infringement of your works of various online rights behavior and its results (including but not limited to witness the RongBaoGe platform under sign a settlement agreement with the infringer,To make the infringer legally use the work by paying for it.</p>
    <p> 3. Online rights protection services provided by Rongbaoge include but are not limited to sending infringement notices, handling infringement links, preserving evidence, signing reconciliation agreements and other rights protection treatment methods.Rongbaoge Platform has the right to make its own judgment on how to protect rights within the scope of the above authorization and to entrust such authorization to a lawyer or other qualified third party.</p>
    <h3> Article 10 Variation of the Agreement </h3 >
    <p> 1, RongBaoGe platform may change according to the national laws and regulations as well as maintaining trading order need to modify this agreement, the supplementary agreement, change after the agreement, the supplementary agreement (hereinafter referred to as the "change") will be through the legal procedure and inform you in the form of agreement, article 9 of the agreement, modify the content shall become effective as of the date of the notice behavior, instead of the original agreement,You should agree and confirm, or pay attention to and read the latest agreement or announcement at any time.</p>
    <p>2. If you do not agree with the effective modification agreement and items, you shall immediately stop using the Services provided by Rongbaoge Platform in accordance with the modified agreement and items;If you use rongbaoge platform services, you are deemed to agree to the changed agreement and contents.</p>
    <h3>Article 11 Termination of the Agreement</h3>
    <p>1. Rongbaoge Platform reserves the right to terminate the use of your account or services at its discretion, including but not limited to non-use of your account for a long time, violation of laws and regulations, violation of this Agreement and other rules of Rongbaoge Platform.</p>
    <p>2. After termination of the Service, Rongbaoge Platform has the right to remove and delete any content you have in Rongbaoge Platform.Rongbaoge platform shall not be responsible for the termination of your account or the closure or deletion of relevant information and files.</p>
    <h3>Article 12 Notice</h3>
    <p>You agree that any notice sent by Rongbaoge platform in the following reasonable manner shall be deemed to have been successfully delivered</p>
    <ul>
      <li>(1) public copy;</li>
      <li>(2) messages pushed by websites and clients;</li>
      <li>(3) Emails, short messages, letters, etc., sent according to the contact information you have reserved in Rongbaoge platform.</li>
    </ul>
    <h3>Article 13 Application, jurisdiction and other aspects of law</h3>
    <p>1. The conclusion, entry into force, interpretation, amendment, supplement, termination, execution and dispute resolution of this Agreement shall be governed by the laws of the People's Republic of China;If not required by law, refer to commercial and/or industry practice.</p>
    <p>2. Disputes arising from users' use of rongbaoge Platform services and related to Rongbaoge Platform services shall be settled by you and Rongbaoge Platform through negotiation.If no agreement can be reached through negotiation, either party shall submit the case to Beijing Arbitration Commission for arbitration in accordance with the commission's arbitration rules in effect at that time.The arbitral award shall be final and binding upon both parties in the dispute.The party at fault determined by the arbitration award shall bear the arbitration fee, notary fee, attorney's fee and other reasonable expenses incurred by the other party in pursuing its fault.During the arbitration, this Agreement shall be performed except for those parts in dispute which are under arbitration by the parties.</p>
    <p>3. Other copyright value-added services referred to in this Agreement refer to the services provided by Rongbaoge Platform to help users increase the copyright value of their works by expanding the industries and fields in which works are applied.</p>

  </el-dialog>
</template>

<script>
export default {
  props: {
    visible: {
      type: Boolean
    }
  },
  methods: {
    handleClose() {
      this.$emit('update:visible', false);
    }
  }
}
</script>

<style lang="less" scoped>
h2 {
  margin: 0.2rem 0;
  font-size: 0.18rem;
  font-weight: bold;
}
h3 {
  margin: 0.2rem 0;
  font-size: 0.16rem;
  font-weight: bold;
}
p {
  font-size: 0.14rem;
  line-height: 0.25rem;
  @media screen and (max-width: 800px) {
    line-height: 0.4rem;
  }
}
ul {
  padding-left: 0.2rem;
  @media screen and (max-width: 800px) {
    padding-left: 0.28rem;
  }
  li {
    font-size: 0.14rem;
    line-height: 0.4rem;
  }
}
</style>
